version: 2
jobs:
  build:
    environment:
      # NODE_ENV: production

    docker:
      - image: cypress/base:10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn --prod --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: yarn lint

      - run: npx launch

      - run: yarn test

